### ISSUE TITLE
npm version is out of date

### ISSUE THREAD

**Issue by gaggle** [ClintH/metalsmith-typeset#2]
The version on npm @ https://www.npmjs.com/package/metalsmith-typeset is version 0.0.1, specifying Typeset version `"typeset": "~0.1.6"`. The version on GitHub is *also* version 0.0.1, but specifies `"typeset": "~0.2.1"`. Looks like fixing #1 did not bump the version, and was not pushed to npm.

**Comment by ClintH** [comment]
Fixed, thanks!
